### ISSUE TITLE
CalculatorValenceChecker is not found for logS calculations

### ISSUE THREAD

**Issue by tdudgeon** [InformaticsMatters/squonk#13]
The solubility predictor does not run correctly as it throws this exception:
```
chemaxon.nfunk.jep.ParseException: Implementation for CalculatorValenceChecker is not found.
at chemaxon.jep.function.Plugin.run(Plugin.java:394)
at chemaxon.nfunk.jep.EvaluatorVisitor.visit(EvaluatorVisitor.java:304)
at chemaxon.nfunk.jep.ASTFunNode.jjtAccept(ASTFunNode.java:63)
at chemaxon.nfunk.jep.EvaluatorVisitor.getValue(EvaluatorVisitor.java:169)
at chemaxon.nfunk.jep.JEP.getValueAsObject(JEP.java:526)
at chemaxon.jep.ChemJEP.evaluate(ChemJEP.java:152)
```
After a lot of digging it appears that this happens when running inside a Java stream, which is very strange.
Now that this is know we can implement a workaround, but we need to work with ChemAxon to resolve this properly and then remove the workaround.

**Comment by tdudgeon** [comment]
A better workaround was found which just involves making the stream sequential to avoid multi-threading.
This retains the benefit of streams, but will result in slower calculations.
Workaround should removed once the underlying problem is resolved.
