### ISSUE TITLE
Delayed response and NPE (InputStream must not be null) when child pod fails

### ISSUE THREAD

**Issue by alanbchristie** [InformaticsMatters/squonk#17]
During testing of Nextflow execution it was noticed that if the dependent (child) pod fails for some reason the squonk Job fails to notice (maybe there are no status updates?). But, when it eventually ends processing (with a **WARNING failed to start. Leaving.** message) the handling of outputs still operates, resulting in a NPE (stack trace below).

The NPE causes the cell in the notebook to get stuck in its executing phase.

The fault is easily reproduced by running in Minishift and disconnecting from the network (because each Pod creation is latest and attempts to contact docker.io).

Can we ...

- Detect pod failure earlier?
- Avoid the NPE on failure?

WARNING: squonk-cell-pod-bdfdb339-22ec-46f7-a591-c10f978dba87 failed to start. Leaving.
Jun 27, 2018 9:13:02 AM org.squonk.execution.runners.OpenShiftRunner execute
INFO: squonk-cell-pod-bdfdb339-22ec-46f7-a591-c10f978dba87 (Execute complete)
Jun 27, 2018 9:13:02 AM org.squonk.execution.steps.impl.DatasetNextflowInDockerExecutorStep doExecute
INFO: Executed in 901.044 seconds with return status of 0
Jun 27, 2018 9:13:02 AM org.squonk.execution.steps.AbstractServiceStep doHandleOutputs
INFO: Handling 1 outputs
Jun 27, 2018 9:13:02 AM org.squonk.execution.steps.AbstractServiceStep handleThinOutput
INFO: Handling thin output for output in /squonk/work/docker/bdfdb339-22ec-46f7-a591-c10f978dba87
Jun 27, 2018 9:13:02 AM org.squonk.execution.variable.VariableManager getValue
INFO: Using read variable handler org.squonk.types.DatasetHandler@7d46169e for type org.squonk.dataset.Dataset
Jun 27, 2018 9:13:02 AM org.squonk.types.DatasetHandler createMetadata
WARNING: No metadata present, using basic default
Jun 27, 2018 9:13:02 AM org.squonk.execution.runners.OpenShiftRunner$PodWatcher eventReceived
INFO: podName=squonk-cell-pod-bdfdb339-22ec-46f7-a591-c10f978dba87 podPhase=Waiting
Jun 27, 2018 9:13:02 AM org.squonk.execution.runners.OpenShiftRunner$PodWatcher eventReceived
INFO: podName=squonk-cell-pod-bdfdb339-22ec-46f7-a591-c10f978dba87 podPhase=Waiting
Jun 27, 2018 9:13:02 AM org.squonk.execution.steps.impl.DatasetNextflowInDockerExecutorStep doExecute
INFO: Results cleaned up
Jun 27, 2018 9:13:02 AM org.squonk.services.cell.CellExecutorRouteBuilder executeJob
WARNING: Failed to execute job bdfdb339-22ec-46f7-a591-c10f978dba87
java.lang.NullPointerException: InputStream must not be null
	at org.squonk.dataset.Dataset.<init>(Dataset.java:208)
	at org.squonk.dataset.Dataset.<init>(Dataset.java:219)
	at org.squonk.types.DatasetHandler.readVariable(DatasetHandler.java:154)
	at org.squonk.types.DatasetHandler.readVariable(DatasetHandler.java:41)
	at org.squonk.execution.variable.VariableManager.getValue(VariableManager.java:136)
	at org.squonk.execution.steps.AbstractServiceStep.handleThinOutput(AbstractServiceStep.java:356)
	at org.squonk.execution.steps.impl.ThinDatasetNextflowInDockerExecutorStep.handleOutput(ThinDatasetNextflowInDockerExecutorStep.java:42)
	at org.squonk.execution.steps.AbstractServiceStep.doHandleOutputs(AbstractServiceStep.java:218)
	at org.squonk.execution.steps.AbstractServiceStep.handleOutputs(AbstractServiceStep.java:205)
	at org.squonk.execution.steps.impl.DatasetNextflowInDockerExecutorStep.doExecute(DatasetNextflowInDockerExecutorStep.java:118)
	at org.squonk.execution.steps.impl.DatasetNextflowInDockerExecutorStep.execute(DatasetNextflowInDockerExecutorStep.java:42)
	at org.squonk.execution.steps.StepExecutor.execute(StepExecutor.java:127)
	at org.squonk.execution.steps.StepExecutor.execute(StepExecutor.java:110)
	at org.squonk.execution.steps.StepExecutor.execute(StepExecutor.java:66)
	at org.squonk.services.cell.CellExecutorRouteBuilder.executeJob(CellExecutorRouteBuilder.java:154)
	at org.squonk.services.cell.CellExecutorRouteBuilder.processJob(CellExecutorRouteBuilder.java:101)
	at org.squonk.services.cell.CellExecutorRouteBuilder.lambda$configure$0(CellExecutorRouteBuilder.java:83)
	at org.apache.camel.processor.DelegateSyncProcessor.process(DelegateSyncProcessor.java:63)
	at org.apache.camel.management.InstrumentationProcessor.process(InstrumentationProcessor.java:77)
	at org.apache.camel.processor.RedeliveryErrorHandler.process(RedeliveryErrorHandler.java:542)
	at org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:197)
	at org.apache.camel.processor.Pipeline.process(Pipeline.java:120)
	at org.apache.camel.processor.Pipeline.process(Pipeline.java:83)
	at org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:197)
	at org.apache.camel.processor.DelegateAsyncProcessor.process(DelegateAsyncProcessor.java:97)
	at org.apache.camel.component.rabbitmq.RabbitConsumer.doHandleDelivery(RabbitConsumer.java:99)
	at org.apache.camel.component.rabbitmq.RabbitConsumer.handleDelivery(RabbitConsumer.java:74)
	at com.rabbitmq.client.impl.ConsumerDispatcher$5.run(ConsumerDispatcher.java:144)
	at com.rabbitmq.client.impl.ConsumerWorkService$WorkPoolRunnable.run(ConsumerWorkService.java:99)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

**Comment by alanbchristie** [comment]
An improved PodWatcher, that detects early instances of pod terminations has been committed to master. the fault can be induced by disconnecting a minishift instance from the internet as the Job runs (ideally a Nextflow Job).
