### ISSUE TITLE
Nextflow RuntimeExecution (AbstractContainerStep.java:108)

### ISSUE THREAD

**Issue by alanbchristie** [InformaticsMatters/squonk#33]
When executing nextflow containers own OpenShift (3.11 in my test) I'm seeing this at the end of the run, resulting in a failed container run...

```
Clustering with descriptor rdkit metric tanimoto and threshold 0.7
Found 31 clusters
Found 31 clusters
Final Clusters: ((27, 12, 21, 25), (8, 1), (5, 4), (35,), (34,), (33,), (32,), (31,), (30,), (29,), (28,), (26,), (24,), (23,), (22,), (20,), (19,), (18,), (17,), (16,), (15,), (14,), (13,), (11,), (10,), (9,), (7,), (6,), (3,), (2,), (0,))

at org.squonk.execution.steps.impl.AbstractContainerStep.handleExecute(AbstractContainerStep.java:108)
  | at org.squonk.execution.steps.impl.AbstractContainerStep.doExecuteForDataSources(AbstractContainerStep.java:81)
  | at org.squonk.execution.steps.impl.AbstractContainerStep.doExecute(AbstractContainerStep.java:55)
  | at org.squonk.execution.steps.AbstractStep.execute(AbstractStep.java:129)
  | at org.squonk.execution.steps.StepExecutor.execute(StepExecutor.java:216)
  | at org.squonk.services.cell.CellExecutorRouteBuilder.executeJob(CellExecutorRouteBuilder.java:155)
  | at org.squonk.services.cell.CellExecutorRouteBuilder.processJob(CellExecutorRouteBuilder.java:100)
  | at org.squonk.services.cell.CellExecutorRouteBuilder.lambda$configure$0(CellExecutorRouteBuilder.java:82)
  | at org.apache.camel.processor.DelegateSyncProcessor.process(DelegateSyncProcessor.java:63)
  | at org.apache.camel.management.InstrumentationProcessor.process(InstrumentationProcessor.java:77)
  | at org.apache.camel.processor.RedeliveryErrorHandler.process(RedeliveryErrorHandler.java:542)
  | at org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:197)
  | at org.apache.camel.processor.Pipeline.process(Pipeline.java:120)
  | at org.apache.camel.processor.Pipeline.process(Pipeline.java:83)
  | at org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:197)
  | at org.apache.camel.processor.DelegateAsyncProcessor.process(DelegateAsyncProcessor.java:97)
  | at org.apache.camel.component.rabbitmq.RabbitConsumer.doHandleDelivery(RabbitConsumer.java:99)
  | at org.apache.camel.component.rabbitmq.RabbitConsumer.handleDelivery(RabbitConsumer.java:74)
  | at com.rabbitmq.client.impl.ConsumerDispatcher$5.run(ConsumerDispatcher.java:144)
  | at com.rabbitmq.client.impl.ConsumerWorkService$WorkPoolRunnable.run(ConsumerWorkService.java:99)
  | at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
  | at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
  | at java.lang.Thread.run(Thread.java:748)
 ```

**Comment by tdudgeon** [comment]
Which service was this? It looks like the butina clustering one, which I thought was using the docker executor.
And it looks like the container execution completed successfully, so could be a problem with the results processing.

**Comment by alanbchristie** [comment]
I was executing `RDKit similarity screening` fed from an SDF Upload of either Kinase or dhfr_standardized.

**Comment by alanbchristie** [comment]
See issue #34
